#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_hello:
  path: /
  controller: App\Controller\HelloController::index

app_hello2:
  path: /hello
  controller: App\Controller\HelloController::index2
