#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\HelloController::index

submit_form:
  path: /submit-form
  controller: App\Controller\HelloController::submitForm

index_list:
  path: /show
  controller: App\Controller\HelloController::index_list

error_page:
    path: /error
    controller: App\Controller\ErrorController::errorPage